spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Local file storage configuration
local-storage-path=${user.home}/tasos-storage

##TODO remove this when starting using profiles in the actual VM on google gloud.
### Database Configuration
spring.datasource.url=jdbc:mysql://
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=never
spring.sql.init.continue-on-error=true
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
